package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.Affix;

import java.util.List;



public interface AffixMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affix
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 07:49:31 CST 2020
=======
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
>>>>>>> 1503dbd79957ac24fedf773d1cfe79dd6dd33285
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affix
     *

    int insert(Affix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affix
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 07:49:31 CST 2020
=======
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
>>>>>>> 1503dbd79957ac24fedf773d1cfe79dd6dd33285
     */
    int insertSelective(Affix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affix
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 07:49:31 CST 2020
=======
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
>>>>>>> 1503dbd79957ac24fedf773d1cfe79dd6dd33285
     */
    Affix selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affix
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 07:49:31 CST 2020
=======
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
>>>>>>> 1503dbd79957ac24fedf773d1cfe79dd6dd33285
     */
    int updateByPrimaryKeySelective(Affix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affix
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 07:49:31 CST 2020
     */
    int updateByPrimaryKey(Affix record);

    List<Affix> selectAffix();



}