package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ConstructionUnit;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConstructionUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_unit
     *
     * @mbg.generated Wed Jun 24 11:28:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_unit
     *
     * @mbg.generated Wed Jun 24 11:28:22 CST 2020
     */
    int insert(ConstructionUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_unit
     *
     * @mbg.generated Wed Jun 24 11:28:22 CST 2020
     */
    int insertSelective(ConstructionUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_unit
     *
     * @mbg.generated Wed Jun 24 11:28:22 CST 2020
     */
    ConstructionUnit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_unit
     *
     * @mbg.generated Wed Jun 24 11:28:22 CST 2020
     */
    int updateByPrimaryKeySelective(ConstructionUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_unit
     *
     * @mbg.generated Wed Jun 24 11:28:22 CST 2020
     */
    int updateByPrimaryKey(ConstructionUnit record);

    List<ConstructionUnit> getConstructionUnit();

    /**
     * 删除记录
     * @param id
     */
    void updateDelFlag(Integer id);

    String getUnitNameById(Integer departmentUnitId);


    Integer[] getByGuideId(@Param("guideId") Integer guideId);
}