package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.Guide;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GuideMapper {

    /**
     * 获取所有指南
     * @param startLine 起始行号
     * @param pageSize 每页大小
     * @return
     */
    List<Guide> selectAllGuide(@Param("startLine") Integer startLine,@Param("pageSize") Integer pageSize);
    /**
     * 根据指南标题 模糊查询列表
     * @param title
     * @return
     */
    List<Guide> selectByTitle(String title);

    /**
     * 根据指南文件号查询
     * @param documentId
     * @return
     */
    List<Guide> selectByDocumentId(@Param("documentId") String documentId);

    /**
     * 根据以上两个条件同时查询
     * @param title
     * @param documentId
     * @return
     */
    List<Guide> selectByTitleAndDocumentId(@Param("title") String title, @Param("documentId") String documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    int insert(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    int insertSelective(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    Guide selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    int updateByPrimaryKeySelective(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    int updateByPrimaryKey(Guide record);

    List<Guide> getGuideByUnitId(int unitId);

    int selectLastInsert();
}