package cn.edu.upc.manage.dao;


import cn.edu.upc.manage.model.Affix;
import cn.edu.upc.manage.model.Modal;
import cn.edu.upc.manage.model.Modal;
import cn.edu.upc.manage.vo.ModalProjectName;


import java.util.List;

public interface ModalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
=======
     * @mbg.generated Thu Jul 02 14:58:06 CST 2020
>>>>>>> 1503dbd79957ac24fedf773d1cfe79dd6dd33285
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
=======
     * @mbg.generated Thu Jul 02 14:58:06 CST 2020
>>>>>>> 1503dbd79957ac24fedf773d1cfe79dd6dd33285
     */
    int insert(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
=======
     * @mbg.generated Thu Jul 02 14:58:06 CST 2020
>>>>>>> 1503dbd79957ac24fedf773d1cfe79dd6dd33285
     */
    int insertSelective(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
=======
     * @mbg.generated Thu Jul 02 14:58:06 CST 2020
>>>>>>> 1503dbd79957ac24fedf773d1cfe79dd6dd33285
     */
    Modal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
=======
     * @mbg.generated Thu Jul 02 14:58:06 CST 2020
>>>>>>> 1503dbd79957ac24fedf773d1cfe79dd6dd33285
     */
    int updateByPrimaryKeySelective(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
<<<<<<< HEAD
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
     */
    int updateByPrimaryKey(Modal record);

    List<Modal> selectModal();

    /**
     * 获取全部竣工信息
     * @return
     */
    List<ModalProjectName> getAllModal();

    /**
     * 根据合同id获取竣工信息
     * @param contractId
     * @return
     */
    List<Modal> getModalByContractId(int contractId);


}