package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.Affix;
import cn.edu.upc.manage.model.Modal;

import java.util.List;

public interface ModalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
     */
    int insert(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
     */
    int insertSelective(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
     */
    Modal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
     */
    int updateByPrimaryKeySelective(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modal
     *
     * @mbg.generated Fri Jul 03 08:16:00 CST 2020
     */
    int updateByPrimaryKey(Modal record);
    List<Modal> selectModal();
}