package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ProjectStore;
import cn.edu.upc.manage.model.ProjectYearPlan;
import cn.edu.upc.manage.model.ProjectYearPlanExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectYearPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_year_plan
     *
     * @mbg.generated Tue Dec 01 15:42:55 CST 2020
     */
    long countByExample(ProjectYearPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_year_plan
     *
     * @mbg.generated Tue Dec 01 15:42:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_year_plan
     *
     * @mbg.generated Tue Dec 01 15:42:55 CST 2020
     */
    int insert(ProjectYearPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_year_plan
     *
     * @mbg.generated Tue Dec 01 15:42:55 CST 2020
     */
    int insertSelective(ProjectYearPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_year_plan
     *
     * @mbg.generated Tue Dec 01 15:42:55 CST 2020
     */
    ProjectYearPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_year_plan
     *
     * @mbg.generated Tue Dec 01 15:42:55 CST 2020
     */
    int updateByPrimaryKeySelective(ProjectYearPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_year_plan
     *
     * @mbg.generated Tue Dec 01 15:42:55 CST 2020
     */
    int updateByPrimaryKey(ProjectYearPlan record);

    void insertList(@Param("list") List<ProjectYearPlan> projectYearPlanList);

    int getByProjectId(@Param("projectId") Integer projectId);


    /**
     * 删除当年计划一个项目
     * @param projectId
     */
    void deleteYearPlanProject(@Param("projectId")Integer projectId);

}