package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ProjectPlan;
import cn.edu.upc.wwp.controller.param.ProjectPlanParam;

import java.util.List;

public interface ProjectPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int insert(ProjectPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int insertSelective(ProjectPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    ProjectPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int updateByPrimaryKeySelective(ProjectPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int updateByPrimaryKey(ProjectPlan record);
    List<ProjectPlanParam> selectProjectPlan();

    List<ProjectPlanParam> getProjectPlanByUnitId(int unitId);

    void update(ProjectPlan record);
}