package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ProjectPlan;
import cn.edu.upc.manage.vo.ProjectPlanDesign;
import cn.edu.upc.manage.vo.ProjectPlanFlag;
import cn.edu.upc.wwp.controller.param.ProjectPlanParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int insert(ProjectPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int insertSelective(ProjectPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    ProjectPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int updateByPrimaryKeySelective(ProjectPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_plan
     *
     * @mbg.generated Thu May 14 20:04:46 CST 2020
     */
    int updateByPrimaryKey(ProjectPlan record);

    /**
     * 在原基础上
     * 增加项目名称查询
     * @param projectName
     * @return
     */
    List<ProjectPlanParam> selectProjectPlan(@Param("projectName")String projectName);

    List<ProjectPlanParam> getProjectPlanByUnitId(@Param("unitId") int unitId,@Param("projectName")String projectName);

    void update(ProjectPlan record);

    List<ProjectPlanFlag> getApprovedProjectByUnitId(@Param("unitId")int unitId,@Param("projectName") String projectName);

    List<ProjectPlanFlag> getCanDesignByUnitId(int unitId);

    List<ProjectPlanDesign> getDesignByUnitId(int unitId);

    List<ProjectPlanDesign> getAllApprovedDesign();
}