package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ProjectStore;

import java.util.List;

public interface ProjectStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_store
     *
     * @mbg.generated Sat May 09 21:34:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_store
     *
     * @mbg.generated Sat May 09 21:34:45 CST 2020
     */
    int insert(ProjectStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_store
     *
     * @mbg.generated Sat May 09 21:34:45 CST 2020
     */
    int insertSelective(ProjectStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_store
     *
     * @mbg.generated Sat May 09 21:34:45 CST 2020
     */
    ProjectStore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_store
     *
     * @mbg.generated Sat May 09 21:34:45 CST 2020
     */
    int updateByPrimaryKeySelective(ProjectStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_store
     *
     * @mbg.generated Sat May 09 21:34:45 CST 2020
     */
    int updateByPrimaryKey(ProjectStore record);
    List<ProjectStore> selectProjectStore();
    List<ProjectStore> searchProjectStore(ProjectStore projectStore);
}