package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.Right;
import cn.edu.upc.manage.model.Rights;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RightsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Sat Jun 13 21:56:25 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Sat Jun 13 21:56:25 CST 2020
     */
    int insert(Rights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Sat Jun 13 21:56:25 CST 2020
     */
    int insertSelective(Rights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Sat Jun 13 21:56:25 CST 2020
     */
    Rights selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Sat Jun 13 21:56:25 CST 2020
     */
    int updateByPrimaryKeySelective(Rights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Sat Jun 13 21:56:25 CST 2020
     */
    int updateByPrimaryKey(Rights record);

    List<Rights> getAllRight();

    void deleteRight(int rightId);

    List<Rights> getByLastId(@Param("lastId") Integer lastId);

    List<Rights> getRightA();

    List<Rights> getRightB(@Param("lastId") Integer lastId);

    List<Rights> getRightC(@Param("lastId") Integer lastId);
}