package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.TenderInformation;
import cn.edu.upc.manage.vo.TenderInformationVo;

import java.util.List;

public interface TenderInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_information
     *
     * @mbg.generated Thu Jun 25 14:42:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_information
     *
     * @mbg.generated Thu Jun 25 14:42:03 CST 2020
     */
    int insert(TenderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_information
     *
     * @mbg.generated Thu Jun 25 14:42:03 CST 2020
     */
    int insertSelective(TenderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_information
     *
     * @mbg.generated Thu Jun 25 14:42:03 CST 2020
     */
    TenderInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_information
     *
     * @mbg.generated Thu Jun 25 14:42:03 CST 2020
     */
    int updateByPrimaryKeySelective(TenderInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tender_information
     *
     * @mbg.generated Thu Jun 25 14:42:03 CST 2020
     */
    int updateByPrimaryKey(TenderInformation record);

    /**
     * 软删除，更新标志位
     * @param id
     */
    int updateDelFlagForId(Integer id);

    /**
     * 返回所有招标，带项目名称
     * @return
     */
    List<TenderInformationVo> getAllTender();

    List<TenderInformation> selectByProjectId(Integer projectId);

    /**
     * 根据项目id删除
     * @param projectId
     */
    void updateDelFlag(Integer projectId);
}