package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.User;
import cn.edu.upc.manage.model.UserWithUnitName;
import cn.edu.upc.manage.vo.UserUnitName;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun May 10 16:37:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun May 10 16:37:05 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun May 10 16:37:05 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun May 10 16:37:05 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun May 10 16:37:05 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun May 10 16:37:05 CST 2020
     */
    int updateByPrimaryKey(User record);



    public User selectByUsername(@Param("username") String username);

    public void changePasswordByEmail(@Param("newPassword") String newPassword,@Param("email") String email);

    public User selectByEmail(@Param("email") String email);

    User selectByTel(@Param("tel") String tel);

    public void changePassword(@Param("newPassword") String newPassword,@Param("id") String id);

    public void deleteUser(@Param("userId") int userId);

    public List<UserWithUnitName> getAllUser();
    public List<UserWithUnitName> getByUsername(String username);

    public void changePasswordByUsername(@Param("newPassword") String newPassword,@Param("username") String username);

    public UserUnitName getUserById(int id);

    public UserUnitName getUserById2(int id);
}