package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ViewRights;

import java.util.List;

public interface ViewRightsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_rights
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    int insert(ViewRights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_rights
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    int insertSelective(ViewRights record);

    List<ViewRights> getAllRight();
}