package cn.edu.upc.manage.model;

import java.util.Date;

public class Affix {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.id
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.project_id
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.contract_id
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.affix_name
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private String affixName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.affix_path
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private String affixPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.create_time
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.del_flag
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.operator
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.operator_ip
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affix.operator_time
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.id
     *
     * @return the value of affix.id
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.id
     *
     * @param id the value for affix.id
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.project_id
     *
     * @return the value of affix.project_id
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.project_id
     *
     * @param projectId the value for affix.project_id
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.contract_id
     *
     * @return the value of affix.contract_id
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.contract_id
     *
     * @param contractId the value for affix.contract_id
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.affix_name
     *
     * @return the value of affix.affix_name
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public String getAffixName() {
        return affixName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.affix_name
     *
     * @param affixName the value for affix.affix_name
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setAffixName(String affixName) {
        this.affixName = affixName == null ? null : affixName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.affix_path
     *
     * @return the value of affix.affix_path
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public String getAffixPath() {
        return affixPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.affix_path
     *
     * @param affixPath the value for affix.affix_path
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setAffixPath(String affixPath) {
        this.affixPath = affixPath == null ? null : affixPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.create_time
     *
     * @return the value of affix.create_time
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.create_time
     *
     * @param createTime the value for affix.create_time
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.del_flag
     *
     * @return the value of affix.del_flag
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.del_flag
     *
     * @param delFlag the value for affix.del_flag
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.operator
     *
     * @return the value of affix.operator
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.operator
     *
     * @param operator the value for affix.operator
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.operator_ip
     *
     * @return the value of affix.operator_ip
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.operator_ip
     *
     * @param operatorIp the value for affix.operator_ip
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affix.operator_time
     *
     * @return the value of affix.operator_time
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affix.operator_time
     *
     * @param operatorTime the value for affix.operator_time
     *
     * @mbg.generated Thu Jul 02 15:00:36 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}