package cn.edu.upc.manage.model;

import java.util.Date;

public class ConstructionProgress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.id
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.project_id
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.contract_id
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.report_time
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private String reportTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.expend_money
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private String expendMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.progress
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private String progress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.approve
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private Integer approve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.creat_time
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.del_flag
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.operator
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.operator_ip
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.operator_time
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.id
     *
     * @return the value of construction_progress.id
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.id
     *
     * @param id the value for construction_progress.id
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.project_id
     *
     * @return the value of construction_progress.project_id
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.project_id
     *
     * @param projectId the value for construction_progress.project_id
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.contract_id
     *
     * @return the value of construction_progress.contract_id
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.contract_id
     *
     * @param contractId the value for construction_progress.contract_id
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.report_time
     *
     * @return the value of construction_progress.report_time
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public String getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.report_time
     *
     * @param reportTime the value for construction_progress.report_time
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setReportTime(String reportTime) {
        this.reportTime = reportTime == null ? null : reportTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.expend_money
     *
     * @return the value of construction_progress.expend_money
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public String getExpendMoney() {
        return expendMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.expend_money
     *
     * @param expendMoney the value for construction_progress.expend_money
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setExpendMoney(String expendMoney) {
        this.expendMoney = expendMoney == null ? null : expendMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.progress
     *
     * @return the value of construction_progress.progress
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public String getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.progress
     *
     * @param progress the value for construction_progress.progress
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setProgress(String progress) {
        this.progress = progress == null ? null : progress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.approve
     *
     * @return the value of construction_progress.approve
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public Integer getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.approve
     *
     * @param approve the value for construction_progress.approve
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setApprove(Integer approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.creat_time
     *
     * @return the value of construction_progress.creat_time
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.creat_time
     *
     * @param creatTime the value for construction_progress.creat_time
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.del_flag
     *
     * @return the value of construction_progress.del_flag
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.del_flag
     *
     * @param delFlag the value for construction_progress.del_flag
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.operator
     *
     * @return the value of construction_progress.operator
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.operator
     *
     * @param operator the value for construction_progress.operator
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.operator_ip
     *
     * @return the value of construction_progress.operator_ip
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.operator_ip
     *
     * @param operatorIp the value for construction_progress.operator_ip
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.operator_time
     *
     * @return the value of construction_progress.operator_time
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.operator_time
     *
     * @param operatorTime the value for construction_progress.operator_time
     *
     * @mbg.generated Tue Jun 30 15:29:42 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}