package cn.edu.upc.manage.model;

import java.util.Date;

public class ConstructionUnit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.id
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.name
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.unit_nature
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private String unitNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.legal_person_number
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private String legalPersonNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.paper_name
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private String paperName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.paper_id
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private String paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.legal_address
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private String legalAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.legal_person
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private Integer legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.unit_finance
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private Integer unitFinance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.remark
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.create_time
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.del_flag
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.operator
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.operator_ip
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_unit.operator_time
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.id
     *
     * @return the value of construction_unit.id
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.id
     *
     * @param id the value for construction_unit.id
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.name
     *
     * @return the value of construction_unit.name
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.name
     *
     * @param name the value for construction_unit.name
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.unit_nature
     *
     * @return the value of construction_unit.unit_nature
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public String getUnitNature() {
        return unitNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.unit_nature
     *
     * @param unitNature the value for construction_unit.unit_nature
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setUnitNature(String unitNature) {
        this.unitNature = unitNature == null ? null : unitNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.legal_person_number
     *
     * @return the value of construction_unit.legal_person_number
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public String getLegalPersonNumber() {
        return legalPersonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.legal_person_number
     *
     * @param legalPersonNumber the value for construction_unit.legal_person_number
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setLegalPersonNumber(String legalPersonNumber) {
        this.legalPersonNumber = legalPersonNumber == null ? null : legalPersonNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.paper_name
     *
     * @return the value of construction_unit.paper_name
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.paper_name
     *
     * @param paperName the value for construction_unit.paper_name
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName == null ? null : paperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.paper_id
     *
     * @return the value of construction_unit.paper_id
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.paper_id
     *
     * @param paperId the value for construction_unit.paper_id
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setPaperId(String paperId) {
        this.paperId = paperId == null ? null : paperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.legal_address
     *
     * @return the value of construction_unit.legal_address
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public String getLegalAddress() {
        return legalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.legal_address
     *
     * @param legalAddress the value for construction_unit.legal_address
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setLegalAddress(String legalAddress) {
        this.legalAddress = legalAddress == null ? null : legalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.legal_person
     *
     * @return the value of construction_unit.legal_person
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public Integer getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.legal_person
     *
     * @param legalPerson the value for construction_unit.legal_person
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setLegalPerson(Integer legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.unit_finance
     *
     * @return the value of construction_unit.unit_finance
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public Integer getUnitFinance() {
        return unitFinance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.unit_finance
     *
     * @param unitFinance the value for construction_unit.unit_finance
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setUnitFinance(Integer unitFinance) {
        this.unitFinance = unitFinance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.remark
     *
     * @return the value of construction_unit.remark
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.remark
     *
     * @param remark the value for construction_unit.remark
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.create_time
     *
     * @return the value of construction_unit.create_time
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.create_time
     *
     * @param createTime the value for construction_unit.create_time
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.del_flag
     *
     * @return the value of construction_unit.del_flag
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.del_flag
     *
     * @param delFlag the value for construction_unit.del_flag
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.operator
     *
     * @return the value of construction_unit.operator
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.operator
     *
     * @param operator the value for construction_unit.operator
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.operator_ip
     *
     * @return the value of construction_unit.operator_ip
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.operator_ip
     *
     * @param operatorIp the value for construction_unit.operator_ip
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_unit.operator_time
     *
     * @return the value of construction_unit.operator_time
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_unit.operator_time
     *
     * @param operatorTime the value for construction_unit.operator_time
     *
     * @mbg.generated Sun May 10 11:40:11 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}