package cn.edu.upc.manage.model;

import java.util.Date;

public class ConstructionProgressAppendix {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress_appendix.id
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress_appendix.progress_id
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    private Integer progressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress_appendix.appendix
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    private String appendix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress_appendix.appendix_name
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    private String appendixName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress_appendix.creat_time
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress_appendix.del_flag
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress_appendix.operator
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress_appendix.operator_ip
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress_appendix.operator_time
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress_appendix.id
     *
     * @return the value of construction_progress_appendix.id
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress_appendix.id
     *
     * @param id the value for construction_progress_appendix.id
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress_appendix.progress_id
     *
     * @return the value of construction_progress_appendix.progress_id
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public Integer getProgressId() {
        return progressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress_appendix.progress_id
     *
     * @param progressId the value for construction_progress_appendix.progress_id
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public void setProgressId(Integer progressId) {
        this.progressId = progressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress_appendix.appendix
     *
     * @return the value of construction_progress_appendix.appendix
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public String getAppendix() {
        return appendix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress_appendix.appendix
     *
     * @param appendix the value for construction_progress_appendix.appendix
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public void setAppendix(String appendix) {
        this.appendix = appendix == null ? null : appendix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress_appendix.appendix_name
     *
     * @return the value of construction_progress_appendix.appendix_name
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public String getAppendixName() {
        return appendixName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress_appendix.appendix_name
     *
     * @param appendixName the value for construction_progress_appendix.appendix_name
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public void setAppendixName(String appendixName) {
        this.appendixName = appendixName == null ? null : appendixName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress_appendix.creat_time
     *
     * @return the value of construction_progress_appendix.creat_time
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress_appendix.creat_time
     *
     * @param creatTime the value for construction_progress_appendix.creat_time
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress_appendix.del_flag
     *
     * @return the value of construction_progress_appendix.del_flag
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress_appendix.del_flag
     *
     * @param delFlag the value for construction_progress_appendix.del_flag
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress_appendix.operator
     *
     * @return the value of construction_progress_appendix.operator
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress_appendix.operator
     *
     * @param operator the value for construction_progress_appendix.operator
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress_appendix.operator_ip
     *
     * @return the value of construction_progress_appendix.operator_ip
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress_appendix.operator_ip
     *
     * @param operatorIp the value for construction_progress_appendix.operator_ip
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress_appendix.operator_time
     *
     * @return the value of construction_progress_appendix.operator_time
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress_appendix.operator_time
     *
     * @param operatorTime the value for construction_progress_appendix.operator_time
     *
     * @mbg.generated Mon Nov 30 17:48:28 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}