package cn.edu.upc.manage.model;

import java.util.Date;

public class Construction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.id
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.construction_name
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    private String constructionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.create_time
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.del_flag
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.operator
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.operator_ip
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.operator_time
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.id
     *
     * @return the value of construction.id
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.id
     *
     * @param id the value for construction.id
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.construction_name
     *
     * @return the value of construction.construction_name
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public String getConstructionName() {
        return constructionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.construction_name
     *
     * @param constructionName the value for construction.construction_name
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public void setConstructionName(String constructionName) {
        this.constructionName = constructionName == null ? null : constructionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.create_time
     *
     * @return the value of construction.create_time
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.create_time
     *
     * @param createTime the value for construction.create_time
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.del_flag
     *
     * @return the value of construction.del_flag
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.del_flag
     *
     * @param delFlag the value for construction.del_flag
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.operator
     *
     * @return the value of construction.operator
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.operator
     *
     * @param operator the value for construction.operator
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.operator_ip
     *
     * @return the value of construction.operator_ip
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.operator_ip
     *
     * @param operatorIp the value for construction.operator_ip
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.operator_time
     *
     * @return the value of construction.operator_time
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.operator_time
     *
     * @param operatorTime the value for construction.operator_time
     *
     * @mbg.generated Thu Jun 04 22:33:31 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}