package cn.edu.upc.manage.model;

import java.util.Date;

public class ConstructionProgress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.id
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.project_id
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.project_name
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.section_id
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private Integer sectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.section_name
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private String sectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.expend_money
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private Float expendMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.pay_money
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private Float payMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.progress
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private Integer progress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.remark
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.creat_time
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.del_flag
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.operator
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.operator_ip
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.operator_time
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private Date operatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_progress.month
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    private String month;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.id
     *
     * @return the value of construction_progress.id
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.id
     *
     * @param id the value for construction_progress.id
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.project_id
     *
     * @return the value of construction_progress.project_id
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.project_id
     *
     * @param projectId the value for construction_progress.project_id
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.project_name
     *
     * @return the value of construction_progress.project_name
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.project_name
     *
     * @param projectName the value for construction_progress.project_name
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.section_id
     *
     * @return the value of construction_progress.section_id
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.section_id
     *
     * @param sectionId the value for construction_progress.section_id
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.section_name
     *
     * @return the value of construction_progress.section_name
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.section_name
     *
     * @param sectionName the value for construction_progress.section_name
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.expend_money
     *
     * @return the value of construction_progress.expend_money
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public Float getExpendMoney() {
        return expendMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.expend_money
     *
     * @param expendMoney the value for construction_progress.expend_money
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setExpendMoney(Float expendMoney) {
        this.expendMoney = expendMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.pay_money
     *
     * @return the value of construction_progress.pay_money
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public Float getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.pay_money
     *
     * @param payMoney the value for construction_progress.pay_money
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setPayMoney(Float payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.progress
     *
     * @return the value of construction_progress.progress
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public Integer getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.progress
     *
     * @param progress the value for construction_progress.progress
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.remark
     *
     * @return the value of construction_progress.remark
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.remark
     *
     * @param remark the value for construction_progress.remark
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.creat_time
     *
     * @return the value of construction_progress.creat_time
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.creat_time
     *
     * @param creatTime the value for construction_progress.creat_time
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.del_flag
     *
     * @return the value of construction_progress.del_flag
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.del_flag
     *
     * @param delFlag the value for construction_progress.del_flag
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.operator
     *
     * @return the value of construction_progress.operator
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.operator
     *
     * @param operator the value for construction_progress.operator
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.operator_ip
     *
     * @return the value of construction_progress.operator_ip
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.operator_ip
     *
     * @param operatorIp the value for construction_progress.operator_ip
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.operator_time
     *
     * @return the value of construction_progress.operator_time
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.operator_time
     *
     * @param operatorTime the value for construction_progress.operator_time
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_progress.month
     *
     * @return the value of construction_progress.month
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_progress.month
     *
     * @param month the value for construction_progress.month
     *
     * @mbg.generated Mon Mar 08 20:40:14 CST 2021
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }
}