package cn.edu.upc.manage.model;

import java.util.Date;

public class ContractTenderRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_tender_relation.id
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_tender_relation.contract_id
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_tender_relation.tender_id
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    private Integer tenderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_tender_relation.create_time
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_tender_relation.del_flag
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_tender_relation.operator
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_tender_relation.operator_ip
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_tender_relation.operator_time
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_tender_relation.id
     *
     * @return the value of contract_tender_relation.id
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_tender_relation.id
     *
     * @param id the value for contract_tender_relation.id
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_tender_relation.contract_id
     *
     * @return the value of contract_tender_relation.contract_id
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_tender_relation.contract_id
     *
     * @param contractId the value for contract_tender_relation.contract_id
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_tender_relation.tender_id
     *
     * @return the value of contract_tender_relation.tender_id
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public Integer getTenderId() {
        return tenderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_tender_relation.tender_id
     *
     * @param tenderId the value for contract_tender_relation.tender_id
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public void setTenderId(Integer tenderId) {
        this.tenderId = tenderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_tender_relation.create_time
     *
     * @return the value of contract_tender_relation.create_time
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_tender_relation.create_time
     *
     * @param createTime the value for contract_tender_relation.create_time
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_tender_relation.del_flag
     *
     * @return the value of contract_tender_relation.del_flag
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_tender_relation.del_flag
     *
     * @param delFlag the value for contract_tender_relation.del_flag
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_tender_relation.operator
     *
     * @return the value of contract_tender_relation.operator
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_tender_relation.operator
     *
     * @param operator the value for contract_tender_relation.operator
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_tender_relation.operator_ip
     *
     * @return the value of contract_tender_relation.operator_ip
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_tender_relation.operator_ip
     *
     * @param operatorIp the value for contract_tender_relation.operator_ip
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_tender_relation.operator_time
     *
     * @return the value of contract_tender_relation.operator_time
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_tender_relation.operator_time
     *
     * @param operatorTime the value for contract_tender_relation.operator_time
     *
     * @mbg.generated Thu Jun 25 11:20:11 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}