package cn.edu.upc.manage.model;

import java.util.Date;

public class ContractInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.id
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.project_id
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.contract_type
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String contractType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.contract_name
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String contractName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.party_a
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String partyA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.party_b
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String partyB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.party_c
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String partyC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.contract_range
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String contractRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.contract_term
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String contractTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.signing_time
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String signingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.contrscy_money
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String contrscyMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.remarks
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.approve
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String approve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.create_time
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.del_flag
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.operator
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.operator_ip
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_information.operator_time
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.id
     *
     * @return the value of contract_information.id
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.id
     *
     * @param id the value for contract_information.id
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.project_id
     *
     * @return the value of contract_information.project_id
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.project_id
     *
     * @param projectId the value for contract_information.project_id
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.contract_type
     *
     * @return the value of contract_information.contract_type
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.contract_type
     *
     * @param contractType the value for contract_information.contract_type
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setContractType(String contractType) {
        this.contractType = contractType == null ? null : contractType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.contract_name
     *
     * @return the value of contract_information.contract_name
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.contract_name
     *
     * @param contractName the value for contract_information.contract_name
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.party_a
     *
     * @return the value of contract_information.party_a
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getPartyA() {
        return partyA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.party_a
     *
     * @param partyA the value for contract_information.party_a
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setPartyA(String partyA) {
        this.partyA = partyA == null ? null : partyA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.party_b
     *
     * @return the value of contract_information.party_b
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getPartyB() {
        return partyB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.party_b
     *
     * @param partyB the value for contract_information.party_b
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setPartyB(String partyB) {
        this.partyB = partyB == null ? null : partyB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.party_c
     *
     * @return the value of contract_information.party_c
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getPartyC() {
        return partyC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.party_c
     *
     * @param partyC the value for contract_information.party_c
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setPartyC(String partyC) {
        this.partyC = partyC == null ? null : partyC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.contract_range
     *
     * @return the value of contract_information.contract_range
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getContractRange() {
        return contractRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.contract_range
     *
     * @param contractRange the value for contract_information.contract_range
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setContractRange(String contractRange) {
        this.contractRange = contractRange == null ? null : contractRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.contract_term
     *
     * @return the value of contract_information.contract_term
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getContractTerm() {
        return contractTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.contract_term
     *
     * @param contractTerm the value for contract_information.contract_term
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setContractTerm(String contractTerm) {
        this.contractTerm = contractTerm == null ? null : contractTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.signing_time
     *
     * @return the value of contract_information.signing_time
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getSigningTime() {
        return signingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.signing_time
     *
     * @param signingTime the value for contract_information.signing_time
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setSigningTime(String signingTime) {
        this.signingTime = signingTime == null ? null : signingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.contrscy_money
     *
     * @return the value of contract_information.contrscy_money
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getContrscyMoney() {
        return contrscyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.contrscy_money
     *
     * @param contrscyMoney the value for contract_information.contrscy_money
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setContrscyMoney(String contrscyMoney) {
        this.contrscyMoney = contrscyMoney == null ? null : contrscyMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.remarks
     *
     * @return the value of contract_information.remarks
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.remarks
     *
     * @param remarks the value for contract_information.remarks
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.approve
     *
     * @return the value of contract_information.approve
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.approve
     *
     * @param approve the value for contract_information.approve
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setApprove(String approve) {
        this.approve = approve == null ? null : approve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.create_time
     *
     * @return the value of contract_information.create_time
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.create_time
     *
     * @param createTime the value for contract_information.create_time
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.del_flag
     *
     * @return the value of contract_information.del_flag
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.del_flag
     *
     * @param delFlag the value for contract_information.del_flag
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.operator
     *
     * @return the value of contract_information.operator
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.operator
     *
     * @param operator the value for contract_information.operator
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.operator_ip
     *
     * @return the value of contract_information.operator_ip
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.operator_ip
     *
     * @param operatorIp the value for contract_information.operator_ip
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_information.operator_time
     *
     * @return the value of contract_information.operator_time
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_information.operator_time
     *
     * @param operatorTime the value for contract_information.operator_time
     *
     * @mbg.generated Sun Jun 14 21:43:59 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}