package cn.edu.upc.manage.model;

import java.util.Date;

public class FeasibilityResearchReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.id
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.project_id
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.construction_address
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private String constructionAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.construction_content
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private String constructionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.investment_amount
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private String investmentAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.remark
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.create_time
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.del_flag
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.operator
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.operator_ip
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.operator_time
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private Date operatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.approve
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private Integer approve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.examine
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private Integer examine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.approve_opinion
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private String approveOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feasibility_research_report.examine_opinion
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    private String examineOpinion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.id
     *
     * @return the value of feasibility_research_report.id
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.id
     *
     * @param id the value for feasibility_research_report.id
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.project_id
     *
     * @return the value of feasibility_research_report.project_id
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.project_id
     *
     * @param projectId the value for feasibility_research_report.project_id
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.construction_address
     *
     * @return the value of feasibility_research_report.construction_address
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public String getConstructionAddress() {
        return constructionAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.construction_address
     *
     * @param constructionAddress the value for feasibility_research_report.construction_address
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setConstructionAddress(String constructionAddress) {
        this.constructionAddress = constructionAddress == null ? null : constructionAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.construction_content
     *
     * @return the value of feasibility_research_report.construction_content
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public String getConstructionContent() {
        return constructionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.construction_content
     *
     * @param constructionContent the value for feasibility_research_report.construction_content
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setConstructionContent(String constructionContent) {
        this.constructionContent = constructionContent == null ? null : constructionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.investment_amount
     *
     * @return the value of feasibility_research_report.investment_amount
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public String getInvestmentAmount() {
        return investmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.investment_amount
     *
     * @param investmentAmount the value for feasibility_research_report.investment_amount
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setInvestmentAmount(String investmentAmount) {
        this.investmentAmount = investmentAmount == null ? null : investmentAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.remark
     *
     * @return the value of feasibility_research_report.remark
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.remark
     *
     * @param remark the value for feasibility_research_report.remark
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.create_time
     *
     * @return the value of feasibility_research_report.create_time
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.create_time
     *
     * @param createTime the value for feasibility_research_report.create_time
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.del_flag
     *
     * @return the value of feasibility_research_report.del_flag
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.del_flag
     *
     * @param delFlag the value for feasibility_research_report.del_flag
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.operator
     *
     * @return the value of feasibility_research_report.operator
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.operator
     *
     * @param operator the value for feasibility_research_report.operator
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.operator_ip
     *
     * @return the value of feasibility_research_report.operator_ip
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.operator_ip
     *
     * @param operatorIp the value for feasibility_research_report.operator_ip
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.operator_time
     *
     * @return the value of feasibility_research_report.operator_time
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.operator_time
     *
     * @param operatorTime the value for feasibility_research_report.operator_time
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.approve
     *
     * @return the value of feasibility_research_report.approve
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public Integer getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.approve
     *
     * @param approve the value for feasibility_research_report.approve
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setApprove(Integer approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.examine
     *
     * @return the value of feasibility_research_report.examine
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public Integer getExamine() {
        return examine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.examine
     *
     * @param examine the value for feasibility_research_report.examine
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setExamine(Integer examine) {
        this.examine = examine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.approve_opinion
     *
     * @return the value of feasibility_research_report.approve_opinion
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public String getApproveOpinion() {
        return approveOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.approve_opinion
     *
     * @param approveOpinion the value for feasibility_research_report.approve_opinion
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setApproveOpinion(String approveOpinion) {
        this.approveOpinion = approveOpinion == null ? null : approveOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feasibility_research_report.examine_opinion
     *
     * @return the value of feasibility_research_report.examine_opinion
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public String getExamineOpinion() {
        return examineOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feasibility_research_report.examine_opinion
     *
     * @param examineOpinion the value for feasibility_research_report.examine_opinion
     *
     * @mbg.generated Sat Jul 04 17:24:02 CST 2020
     */
    public void setExamineOpinion(String examineOpinion) {
        this.examineOpinion = examineOpinion == null ? null : examineOpinion.trim();
    }
}