package cn.edu.upc.manage.model;

import java.util.Date;

public class Guide {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.id
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.title
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.document_id
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.publish_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.end_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.content
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.appendix
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private String appendix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.create_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.del_flag
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.operator
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.operator_ip
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.operator_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.id
     *
     * @return the value of guide.id
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.id
     *
     * @param id the value for guide.id
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.title
     *
     * @return the value of guide.title
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.title
     *
     * @param title the value for guide.title
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.document_id
     *
     * @return the value of guide.document_id
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.document_id
     *
     * @param documentId the value for guide.document_id
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId == null ? null : documentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.publish_time
     *
     * @return the value of guide.publish_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.publish_time
     *
     * @param publishTime the value for guide.publish_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.end_time
     *
     * @return the value of guide.end_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.end_time
     *
     * @param endTime the value for guide.end_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.content
     *
     * @return the value of guide.content
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.content
     *
     * @param content the value for guide.content
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.appendix
     *
     * @return the value of guide.appendix
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public String getAppendix() {
        return appendix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.appendix
     *
     * @param appendix the value for guide.appendix
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setAppendix(String appendix) {
        this.appendix = appendix == null ? null : appendix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.create_time
     *
     * @return the value of guide.create_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.create_time
     *
     * @param createTime the value for guide.create_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.del_flag
     *
     * @return the value of guide.del_flag
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.del_flag
     *
     * @param delFlag the value for guide.del_flag
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.operator
     *
     * @return the value of guide.operator
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.operator
     *
     * @param operator the value for guide.operator
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.operator_ip
     *
     * @return the value of guide.operator_ip
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.operator_ip
     *
     * @param operatorIp the value for guide.operator_ip
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.operator_time
     *
     * @return the value of guide.operator_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.operator_time
     *
     * @param operatorTime the value for guide.operator_time
     *
     * @mbg.generated Fri May 08 19:37:32 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}