package cn.edu.upc.manage.model;

import java.util.Date;

public class GuideOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.id
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.guide_id
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private Integer guideId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.title_a
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private String titleA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.title_b
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private String titleB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.title_c
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private String titleC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.create_time
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.del_flag
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.operator
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.operator_ip
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_option.operator_time
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.id
     *
     * @return the value of guide_option.id
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.id
     *
     * @param id the value for guide_option.id
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.guide_id
     *
     * @return the value of guide_option.guide_id
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public Integer getGuideId() {
        return guideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.guide_id
     *
     * @param guideId the value for guide_option.guide_id
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setGuideId(Integer guideId) {
        this.guideId = guideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.title_a
     *
     * @return the value of guide_option.title_a
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public String getTitleA() {
        return titleA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.title_a
     *
     * @param titleA the value for guide_option.title_a
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setTitleA(String titleA) {
        this.titleA = titleA == null ? null : titleA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.title_b
     *
     * @return the value of guide_option.title_b
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public String getTitleB() {
        return titleB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.title_b
     *
     * @param titleB the value for guide_option.title_b
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setTitleB(String titleB) {
        this.titleB = titleB == null ? null : titleB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.title_c
     *
     * @return the value of guide_option.title_c
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public String getTitleC() {
        return titleC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.title_c
     *
     * @param titleC the value for guide_option.title_c
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setTitleC(String titleC) {
        this.titleC = titleC == null ? null : titleC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.create_time
     *
     * @return the value of guide_option.create_time
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.create_time
     *
     * @param createTime the value for guide_option.create_time
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.del_flag
     *
     * @return the value of guide_option.del_flag
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.del_flag
     *
     * @param delFlag the value for guide_option.del_flag
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.operator
     *
     * @return the value of guide_option.operator
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.operator
     *
     * @param operator the value for guide_option.operator
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.operator_ip
     *
     * @return the value of guide_option.operator_ip
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.operator_ip
     *
     * @param operatorIp the value for guide_option.operator_ip
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_option.operator_time
     *
     * @return the value of guide_option.operator_time
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_option.operator_time
     *
     * @param operatorTime the value for guide_option.operator_time
     *
     * @mbg.generated Mon Nov 23 11:43:07 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}