package cn.edu.upc.manage.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Guide {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.id
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.title
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.document_id
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.publish_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.end_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.content
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.appendix
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String appendix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.create_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.del_flag
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.operator
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.operator_ip
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.operator_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private Date operatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.year
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.policy_plan
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String policyPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.industrial_distribution
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String industrialDistribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.invest_field
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String investField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.invest_suggestion
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String investSuggestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide.other_requirement
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    private String otherRequirement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.id
     *
     * @return the value of guide.id
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.id
     *
     * @param id the value for guide.id
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.title
     *
     * @return the value of guide.title
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.title
     *
     * @param title the value for guide.title
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.document_id
     *
     * @return the value of guide.document_id
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.document_id
     *
     * @param documentId the value for guide.document_id
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId == null ? null : documentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.publish_time
     *
     * @return the value of guide.publish_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.publish_time
     *
     * @param publishTime the value for guide.publish_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.end_time
     *
     * @return the value of guide.end_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.end_time
     *
     * @param endTime the value for guide.end_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.content
     *
     * @return the value of guide.content
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.content
     *
     * @param content the value for guide.content
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.appendix
     *
     * @return the value of guide.appendix
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getAppendix() {
        return appendix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.appendix
     *
     * @param appendix the value for guide.appendix
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setAppendix(String appendix) {
        this.appendix = appendix == null ? null : appendix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.create_time
     *
     * @return the value of guide.create_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.create_time
     *
     * @param createTime the value for guide.create_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.del_flag
     *
     * @return the value of guide.del_flag
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.del_flag
     *
     * @param delFlag the value for guide.del_flag
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.operator
     *
     * @return the value of guide.operator
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.operator
     *
     * @param operator the value for guide.operator
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.operator_ip
     *
     * @return the value of guide.operator_ip
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.operator_ip
     *
     * @param operatorIp the value for guide.operator_ip
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.operator_time
     *
     * @return the value of guide.operator_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.operator_time
     *
     * @param operatorTime the value for guide.operator_time
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.year
     *
     * @return the value of guide.year
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.year
     *
     * @param year the value for guide.year
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.policy_plan
     *
     * @return the value of guide.policy_plan
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getPolicyPlan() {
        return policyPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.policy_plan
     *
     * @param policyPlan the value for guide.policy_plan
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setPolicyPlan(String policyPlan) {
        this.policyPlan = policyPlan == null ? null : policyPlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.industrial_distribution
     *
     * @return the value of guide.industrial_distribution
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getIndustrialDistribution() {
        return industrialDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.industrial_distribution
     *
     * @param industrialDistribution the value for guide.industrial_distribution
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setIndustrialDistribution(String industrialDistribution) {
        this.industrialDistribution = industrialDistribution == null ? null : industrialDistribution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.invest_field
     *
     * @return the value of guide.invest_field
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getInvestField() {
        return investField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.invest_field
     *
     * @param investField the value for guide.invest_field
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setInvestField(String investField) {
        this.investField = investField == null ? null : investField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.invest_suggestion
     *
     * @return the value of guide.invest_suggestion
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getInvestSuggestion() {
        return investSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.invest_suggestion
     *
     * @param investSuggestion the value for guide.invest_suggestion
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setInvestSuggestion(String investSuggestion) {
        this.investSuggestion = investSuggestion == null ? null : investSuggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide.other_requirement
     *
     * @return the value of guide.other_requirement
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public String getOtherRequirement() {
        return otherRequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide.other_requirement
     *
     * @param otherRequirement the value for guide.other_requirement
     *
     * @mbg.generated Thu Nov 26 16:25:58 CST 2020
     */
    public void setOtherRequirement(String otherRequirement) {
        this.otherRequirement = otherRequirement == null ? null : otherRequirement.trim();
    }
}