package cn.edu.upc.manage.model;

import java.util.Date;

public class PredesignReportAppendix {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.id
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.project_id
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.appendix_name
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private String appendixName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.appendix
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private String appendix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.uploader
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private String uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.create_time
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.del_flag
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.operator
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.operator_ip
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.operator_time
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private Date operatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.approve
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private Integer approve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predesign_report_appendix.examine
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    private Integer examine;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.id
     *
     * @return the value of predesign_report_appendix.id
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.id
     *
     * @param id the value for predesign_report_appendix.id
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.project_id
     *
     * @return the value of predesign_report_appendix.project_id
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.project_id
     *
     * @param projectId the value for predesign_report_appendix.project_id
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.appendix_name
     *
     * @return the value of predesign_report_appendix.appendix_name
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public String getAppendixName() {
        return appendixName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.appendix_name
     *
     * @param appendixName the value for predesign_report_appendix.appendix_name
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setAppendixName(String appendixName) {
        this.appendixName = appendixName == null ? null : appendixName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.appendix
     *
     * @return the value of predesign_report_appendix.appendix
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public String getAppendix() {
        return appendix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.appendix
     *
     * @param appendix the value for predesign_report_appendix.appendix
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setAppendix(String appendix) {
        this.appendix = appendix == null ? null : appendix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.uploader
     *
     * @return the value of predesign_report_appendix.uploader
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public String getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.uploader
     *
     * @param uploader the value for predesign_report_appendix.uploader
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setUploader(String uploader) {
        this.uploader = uploader == null ? null : uploader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.create_time
     *
     * @return the value of predesign_report_appendix.create_time
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.create_time
     *
     * @param createTime the value for predesign_report_appendix.create_time
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.del_flag
     *
     * @return the value of predesign_report_appendix.del_flag
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.del_flag
     *
     * @param delFlag the value for predesign_report_appendix.del_flag
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.operator
     *
     * @return the value of predesign_report_appendix.operator
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.operator
     *
     * @param operator the value for predesign_report_appendix.operator
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.operator_ip
     *
     * @return the value of predesign_report_appendix.operator_ip
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.operator_ip
     *
     * @param operatorIp the value for predesign_report_appendix.operator_ip
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.operator_time
     *
     * @return the value of predesign_report_appendix.operator_time
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.operator_time
     *
     * @param operatorTime the value for predesign_report_appendix.operator_time
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.approve
     *
     * @return the value of predesign_report_appendix.approve
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public Integer getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.approve
     *
     * @param approve the value for predesign_report_appendix.approve
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setApprove(Integer approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predesign_report_appendix.examine
     *
     * @return the value of predesign_report_appendix.examine
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public Integer getExamine() {
        return examine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predesign_report_appendix.examine
     *
     * @param examine the value for predesign_report_appendix.examine
     *
     * @mbg.generated Fri Jun 26 20:08:51 CST 2020
     */
    public void setExamine(Integer examine) {
        this.examine = examine;
    }
}