package cn.edu.upc.manage.model;

import java.util.Date;

public class ProjectVerification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_verification.id
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_verification.project_id
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_verification.verification_name
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    private String verificationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_verification.verification_flag
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    private Integer verificationFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_verification.create_time
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_verification.del_flag
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_verification.operator
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_verification.operator_time
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_verification.id
     *
     * @return the value of project_verification.id
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_verification.id
     *
     * @param id the value for project_verification.id
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_verification.project_id
     *
     * @return the value of project_verification.project_id
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_verification.project_id
     *
     * @param projectId the value for project_verification.project_id
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_verification.verification_name
     *
     * @return the value of project_verification.verification_name
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public String getVerificationName() {
        return verificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_verification.verification_name
     *
     * @param verificationName the value for project_verification.verification_name
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public void setVerificationName(String verificationName) {
        this.verificationName = verificationName == null ? null : verificationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_verification.verification_flag
     *
     * @return the value of project_verification.verification_flag
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public Integer getVerificationFlag() {
        return verificationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_verification.verification_flag
     *
     * @param verificationFlag the value for project_verification.verification_flag
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public void setVerificationFlag(Integer verificationFlag) {
        this.verificationFlag = verificationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_verification.create_time
     *
     * @return the value of project_verification.create_time
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_verification.create_time
     *
     * @param createTime the value for project_verification.create_time
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_verification.del_flag
     *
     * @return the value of project_verification.del_flag
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_verification.del_flag
     *
     * @param delFlag the value for project_verification.del_flag
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_verification.operator
     *
     * @return the value of project_verification.operator
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_verification.operator
     *
     * @param operator the value for project_verification.operator
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_verification.operator_time
     *
     * @return the value of project_verification.operator_time
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_verification.operator_time
     *
     * @param operatorTime the value for project_verification.operator_time
     *
     * @mbg.generated Fri Mar 19 21:31:03 CST 2021
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}