package cn.edu.upc.manage.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public ProjectListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceIsNull() {
            addCriterion("project_place is null");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceIsNotNull() {
            addCriterion("project_place is not null");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceEqualTo(String value) {
            addCriterion("project_place =", value, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceNotEqualTo(String value) {
            addCriterion("project_place <>", value, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceGreaterThan(String value) {
            addCriterion("project_place >", value, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("project_place >=", value, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceLessThan(String value) {
            addCriterion("project_place <", value, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceLessThanOrEqualTo(String value) {
            addCriterion("project_place <=", value, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceLike(String value) {
            addCriterion("project_place like", value, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceNotLike(String value) {
            addCriterion("project_place not like", value, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceIn(List<String> values) {
            addCriterion("project_place in", values, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceNotIn(List<String> values) {
            addCriterion("project_place not in", values, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceBetween(String value1, String value2) {
            addCriterion("project_place between", value1, value2, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andProjectPlaceNotBetween(String value1, String value2) {
            addCriterion("project_place not between", value1, value2, "projectPlace");
            return (Criteria) this;
        }

        public Criteria andApproveContentIsNull() {
            addCriterion("approve_content is null");
            return (Criteria) this;
        }

        public Criteria andApproveContentIsNotNull() {
            addCriterion("approve_content is not null");
            return (Criteria) this;
        }

        public Criteria andApproveContentEqualTo(Integer value) {
            addCriterion("approve_content =", value, "approveContent");
            return (Criteria) this;
        }

        public Criteria andApproveContentNotEqualTo(Integer value) {
            addCriterion("approve_content <>", value, "approveContent");
            return (Criteria) this;
        }

        public Criteria andApproveContentGreaterThan(Integer value) {
            addCriterion("approve_content >", value, "approveContent");
            return (Criteria) this;
        }

        public Criteria andApproveContentGreaterThanOrEqualTo(Integer value) {
            addCriterion("approve_content >=", value, "approveContent");
            return (Criteria) this;
        }

        public Criteria andApproveContentLessThan(Integer value) {
            addCriterion("approve_content <", value, "approveContent");
            return (Criteria) this;
        }

        public Criteria andApproveContentLessThanOrEqualTo(Integer value) {
            addCriterion("approve_content <=", value, "approveContent");
            return (Criteria) this;
        }

        public Criteria andApproveContentIn(List<Integer> values) {
            addCriterion("approve_content in", values, "approveContent");
            return (Criteria) this;
        }

        public Criteria andApproveContentNotIn(List<Integer> values) {
            addCriterion("approve_content not in", values, "approveContent");
            return (Criteria) this;
        }

        public Criteria andApproveContentBetween(Integer value1, Integer value2) {
            addCriterion("approve_content between", value1, value2, "approveContent");
            return (Criteria) this;
        }

        public Criteria andApproveContentNotBetween(Integer value1, Integer value2) {
            addCriterion("approve_content not between", value1, value2, "approveContent");
            return (Criteria) this;
        }

        public Criteria andMoneySourceIsNull() {
            addCriterion("money_source is null");
            return (Criteria) this;
        }

        public Criteria andMoneySourceIsNotNull() {
            addCriterion("money_source is not null");
            return (Criteria) this;
        }

        public Criteria andMoneySourceEqualTo(String value) {
            addCriterion("money_source =", value, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceNotEqualTo(String value) {
            addCriterion("money_source <>", value, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceGreaterThan(String value) {
            addCriterion("money_source >", value, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceGreaterThanOrEqualTo(String value) {
            addCriterion("money_source >=", value, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceLessThan(String value) {
            addCriterion("money_source <", value, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceLessThanOrEqualTo(String value) {
            addCriterion("money_source <=", value, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceLike(String value) {
            addCriterion("money_source like", value, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceNotLike(String value) {
            addCriterion("money_source not like", value, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceIn(List<String> values) {
            addCriterion("money_source in", values, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceNotIn(List<String> values) {
            addCriterion("money_source not in", values, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceBetween(String value1, String value2) {
            addCriterion("money_source between", value1, value2, "moneySource");
            return (Criteria) this;
        }

        public Criteria andMoneySourceNotBetween(String value1, String value2) {
            addCriterion("money_source not between", value1, value2, "moneySource");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestIsNull() {
            addCriterion("estimate_invest is null");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestIsNotNull() {
            addCriterion("estimate_invest is not null");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestEqualTo(Float value) {
            addCriterion("estimate_invest =", value, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestNotEqualTo(Float value) {
            addCriterion("estimate_invest <>", value, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestGreaterThan(Float value) {
            addCriterion("estimate_invest >", value, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestGreaterThanOrEqualTo(Float value) {
            addCriterion("estimate_invest >=", value, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestLessThan(Float value) {
            addCriterion("estimate_invest <", value, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestLessThanOrEqualTo(Float value) {
            addCriterion("estimate_invest <=", value, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestIn(List<Float> values) {
            addCriterion("estimate_invest in", values, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestNotIn(List<Float> values) {
            addCriterion("estimate_invest not in", values, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestBetween(Float value1, Float value2) {
            addCriterion("estimate_invest between", value1, value2, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstimateInvestNotBetween(Float value1, Float value2) {
            addCriterion("estimate_invest not between", value1, value2, "estimateInvest");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureIsNull() {
            addCriterion("establish_nature is null");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureIsNotNull() {
            addCriterion("establish_nature is not null");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureEqualTo(String value) {
            addCriterion("establish_nature =", value, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureNotEqualTo(String value) {
            addCriterion("establish_nature <>", value, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureGreaterThan(String value) {
            addCriterion("establish_nature >", value, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureGreaterThanOrEqualTo(String value) {
            addCriterion("establish_nature >=", value, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureLessThan(String value) {
            addCriterion("establish_nature <", value, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureLessThanOrEqualTo(String value) {
            addCriterion("establish_nature <=", value, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureLike(String value) {
            addCriterion("establish_nature like", value, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureNotLike(String value) {
            addCriterion("establish_nature not like", value, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureIn(List<String> values) {
            addCriterion("establish_nature in", values, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureNotIn(List<String> values) {
            addCriterion("establish_nature not in", values, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureBetween(String value1, String value2) {
            addCriterion("establish_nature between", value1, value2, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEstablishNatureNotBetween(String value1, String value2) {
            addCriterion("establish_nature not between", value1, value2, "establishNature");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleIsNull() {
            addCriterion("eatablish_scale is null");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleIsNotNull() {
            addCriterion("eatablish_scale is not null");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleEqualTo(Float value) {
            addCriterion("eatablish_scale =", value, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleNotEqualTo(Float value) {
            addCriterion("eatablish_scale <>", value, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleGreaterThan(Float value) {
            addCriterion("eatablish_scale >", value, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleGreaterThanOrEqualTo(Float value) {
            addCriterion("eatablish_scale >=", value, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleLessThan(Float value) {
            addCriterion("eatablish_scale <", value, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleLessThanOrEqualTo(Float value) {
            addCriterion("eatablish_scale <=", value, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleIn(List<Float> values) {
            addCriterion("eatablish_scale in", values, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleNotIn(List<Float> values) {
            addCriterion("eatablish_scale not in", values, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleBetween(Float value1, Float value2) {
            addCriterion("eatablish_scale between", value1, value2, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andEatablishScaleNotBetween(Float value1, Float value2) {
            addCriterion("eatablish_scale not between", value1, value2, "eatablishScale");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceIsNull() {
            addCriterion("approval_price is null");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceIsNotNull() {
            addCriterion("approval_price is not null");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceEqualTo(Float value) {
            addCriterion("approval_price =", value, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceNotEqualTo(Float value) {
            addCriterion("approval_price <>", value, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceGreaterThan(Float value) {
            addCriterion("approval_price >", value, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("approval_price >=", value, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceLessThan(Float value) {
            addCriterion("approval_price <", value, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceLessThanOrEqualTo(Float value) {
            addCriterion("approval_price <=", value, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceIn(List<Float> values) {
            addCriterion("approval_price in", values, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceNotIn(List<Float> values) {
            addCriterion("approval_price not in", values, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceBetween(Float value1, Float value2) {
            addCriterion("approval_price between", value1, value2, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andApprovalPriceNotBetween(Float value1, Float value2) {
            addCriterion("approval_price not between", value1, value2, "approvalPrice");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeIsNull() {
            addCriterion("operator_time is null");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeIsNotNull() {
            addCriterion("operator_time is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeEqualTo(Date value) {
            addCriterion("operator_time =", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeNotEqualTo(Date value) {
            addCriterion("operator_time <>", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeGreaterThan(Date value) {
            addCriterion("operator_time >", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("operator_time >=", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeLessThan(Date value) {
            addCriterion("operator_time <", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeLessThanOrEqualTo(Date value) {
            addCriterion("operator_time <=", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeIn(List<Date> values) {
            addCriterion("operator_time in", values, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeNotIn(List<Date> values) {
            addCriterion("operator_time not in", values, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeBetween(Date value1, Date value2) {
            addCriterion("operator_time between", value1, value2, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeNotBetween(Date value1, Date value2) {
            addCriterion("operator_time not between", value1, value2, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andListIsNull() {
            addCriterion("list is null");
            return (Criteria) this;
        }

        public Criteria andListIsNotNull() {
            addCriterion("list is not null");
            return (Criteria) this;
        }

        public Criteria andListEqualTo(String value) {
            addCriterion("list =", value, "list");
            return (Criteria) this;
        }

        public Criteria andListNotEqualTo(String value) {
            addCriterion("list <>", value, "list");
            return (Criteria) this;
        }

        public Criteria andListGreaterThan(String value) {
            addCriterion("list >", value, "list");
            return (Criteria) this;
        }

        public Criteria andListGreaterThanOrEqualTo(String value) {
            addCriterion("list >=", value, "list");
            return (Criteria) this;
        }

        public Criteria andListLessThan(String value) {
            addCriterion("list <", value, "list");
            return (Criteria) this;
        }

        public Criteria andListLessThanOrEqualTo(String value) {
            addCriterion("list <=", value, "list");
            return (Criteria) this;
        }

        public Criteria andListLike(String value) {
            addCriterion("list like", value, "list");
            return (Criteria) this;
        }

        public Criteria andListNotLike(String value) {
            addCriterion("list not like", value, "list");
            return (Criteria) this;
        }

        public Criteria andListIn(List<String> values) {
            addCriterion("list in", values, "list");
            return (Criteria) this;
        }

        public Criteria andListNotIn(List<String> values) {
            addCriterion("list not in", values, "list");
            return (Criteria) this;
        }

        public Criteria andListBetween(String value1, String value2) {
            addCriterion("list between", value1, value2, "list");
            return (Criteria) this;
        }

        public Criteria andListNotBetween(String value1, String value2) {
            addCriterion("list not between", value1, value2, "list");
            return (Criteria) this;
        }

        public Criteria andApproveIsNull() {
            addCriterion("approve is null");
            return (Criteria) this;
        }

        public Criteria andApproveIsNotNull() {
            addCriterion("approve is not null");
            return (Criteria) this;
        }

        public Criteria andApproveEqualTo(Integer value) {
            addCriterion("approve =", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveNotEqualTo(Integer value) {
            addCriterion("approve <>", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveGreaterThan(Integer value) {
            addCriterion("approve >", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveGreaterThanOrEqualTo(Integer value) {
            addCriterion("approve >=", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveLessThan(Integer value) {
            addCriterion("approve <", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveLessThanOrEqualTo(Integer value) {
            addCriterion("approve <=", value, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveIn(List<Integer> values) {
            addCriterion("approve in", values, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveNotIn(List<Integer> values) {
            addCriterion("approve not in", values, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveBetween(Integer value1, Integer value2) {
            addCriterion("approve between", value1, value2, "approve");
            return (Criteria) this;
        }

        public Criteria andApproveNotBetween(Integer value1, Integer value2) {
            addCriterion("approve not between", value1, value2, "approve");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneIsNull() {
            addCriterion("verification_opinion_one is null");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneIsNotNull() {
            addCriterion("verification_opinion_one is not null");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneEqualTo(String value) {
            addCriterion("verification_opinion_one =", value, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneNotEqualTo(String value) {
            addCriterion("verification_opinion_one <>", value, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneGreaterThan(String value) {
            addCriterion("verification_opinion_one >", value, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneGreaterThanOrEqualTo(String value) {
            addCriterion("verification_opinion_one >=", value, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneLessThan(String value) {
            addCriterion("verification_opinion_one <", value, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneLessThanOrEqualTo(String value) {
            addCriterion("verification_opinion_one <=", value, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneLike(String value) {
            addCriterion("verification_opinion_one like", value, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneNotLike(String value) {
            addCriterion("verification_opinion_one not like", value, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneIn(List<String> values) {
            addCriterion("verification_opinion_one in", values, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneNotIn(List<String> values) {
            addCriterion("verification_opinion_one not in", values, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneBetween(String value1, String value2) {
            addCriterion("verification_opinion_one between", value1, value2, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionOneNotBetween(String value1, String value2) {
            addCriterion("verification_opinion_one not between", value1, value2, "verificationOpinionOne");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoIsNull() {
            addCriterion("verification_opinion_two is null");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoIsNotNull() {
            addCriterion("verification_opinion_two is not null");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoEqualTo(String value) {
            addCriterion("verification_opinion_two =", value, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoNotEqualTo(String value) {
            addCriterion("verification_opinion_two <>", value, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoGreaterThan(String value) {
            addCriterion("verification_opinion_two >", value, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoGreaterThanOrEqualTo(String value) {
            addCriterion("verification_opinion_two >=", value, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoLessThan(String value) {
            addCriterion("verification_opinion_two <", value, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoLessThanOrEqualTo(String value) {
            addCriterion("verification_opinion_two <=", value, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoLike(String value) {
            addCriterion("verification_opinion_two like", value, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoNotLike(String value) {
            addCriterion("verification_opinion_two not like", value, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoIn(List<String> values) {
            addCriterion("verification_opinion_two in", values, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoNotIn(List<String> values) {
            addCriterion("verification_opinion_two not in", values, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoBetween(String value1, String value2) {
            addCriterion("verification_opinion_two between", value1, value2, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionTwoNotBetween(String value1, String value2) {
            addCriterion("verification_opinion_two not between", value1, value2, "verificationOpinionTwo");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeIsNull() {
            addCriterion("verification_opinion_three is null");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeIsNotNull() {
            addCriterion("verification_opinion_three is not null");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeEqualTo(String value) {
            addCriterion("verification_opinion_three =", value, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeNotEqualTo(String value) {
            addCriterion("verification_opinion_three <>", value, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeGreaterThan(String value) {
            addCriterion("verification_opinion_three >", value, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeGreaterThanOrEqualTo(String value) {
            addCriterion("verification_opinion_three >=", value, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeLessThan(String value) {
            addCriterion("verification_opinion_three <", value, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeLessThanOrEqualTo(String value) {
            addCriterion("verification_opinion_three <=", value, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeLike(String value) {
            addCriterion("verification_opinion_three like", value, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeNotLike(String value) {
            addCriterion("verification_opinion_three not like", value, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeIn(List<String> values) {
            addCriterion("verification_opinion_three in", values, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeNotIn(List<String> values) {
            addCriterion("verification_opinion_three not in", values, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeBetween(String value1, String value2) {
            addCriterion("verification_opinion_three between", value1, value2, "verificationOpinionThree");
            return (Criteria) this;
        }

        public Criteria andVerificationOpinionThreeNotBetween(String value1, String value2) {
            addCriterion("verification_opinion_three not between", value1, value2, "verificationOpinionThree");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_list
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 26 19:59:42 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_list
     *
     * @mbg.generated Fri Mar 26 19:59:42 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}