package cn.edu.upc.manage.model;

public class ViewRightsRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights_role.role_id
     *
     * @mbg.generated Sun Jun 14 16:36:14 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights_role.role_name
     *
     * @mbg.generated Sun Jun 14 16:36:14 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights_role.rights_name
     *
     * @mbg.generated Sun Jun 14 16:36:14 CST 2020
     */
    private String rightsName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights_role.role_id
     *
     * @return the value of view_rights_role.role_id
     *
     * @mbg.generated Sun Jun 14 16:36:14 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights_role.role_id
     *
     * @param roleId the value for view_rights_role.role_id
     *
     * @mbg.generated Sun Jun 14 16:36:14 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights_role.role_name
     *
     * @return the value of view_rights_role.role_name
     *
     * @mbg.generated Sun Jun 14 16:36:14 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights_role.role_name
     *
     * @param roleName the value for view_rights_role.role_name
     *
     * @mbg.generated Sun Jun 14 16:36:14 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights_role.rights_name
     *
     * @return the value of view_rights_role.rights_name
     *
     * @mbg.generated Sun Jun 14 16:36:14 CST 2020
     */
    public String getRightsName() {
        return rightsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights_role.rights_name
     *
     * @param rightsName the value for view_rights_role.rights_name
     *
     * @mbg.generated Sun Jun 14 16:36:14 CST 2020
     */
    public void setRightsName(String rightsName) {
        this.rightsName = rightsName == null ? null : rightsName.trim();
    }
}