package cn.edu.upc.manage.model;

import java.util.Date;

public class ViewRights {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.id
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.right_name
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private String rightName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.last_id
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private Integer lastId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.url
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.create_time
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.del_flag
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.operator
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.operator_id
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private String operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.operator_time
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private Date operatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_rights.last_right_name
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    private String lastRightName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.id
     *
     * @return the value of view_rights.id
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.id
     *
     * @param id the value for view_rights.id
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.right_name
     *
     * @return the value of view_rights.right_name
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.right_name
     *
     * @param rightName the value for view_rights.right_name
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setRightName(String rightName) {
        this.rightName = rightName == null ? null : rightName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.last_id
     *
     * @return the value of view_rights.last_id
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public Integer getLastId() {
        return lastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.last_id
     *
     * @param lastId the value for view_rights.last_id
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setLastId(Integer lastId) {
        this.lastId = lastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.url
     *
     * @return the value of view_rights.url
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.url
     *
     * @param url the value for view_rights.url
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.create_time
     *
     * @return the value of view_rights.create_time
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.create_time
     *
     * @param createTime the value for view_rights.create_time
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.del_flag
     *
     * @return the value of view_rights.del_flag
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.del_flag
     *
     * @param delFlag the value for view_rights.del_flag
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.operator
     *
     * @return the value of view_rights.operator
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.operator
     *
     * @param operator the value for view_rights.operator
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.operator_id
     *
     * @return the value of view_rights.operator_id
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.operator_id
     *
     * @param operatorId the value for view_rights.operator_id
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.operator_time
     *
     * @return the value of view_rights.operator_time
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.operator_time
     *
     * @param operatorTime the value for view_rights.operator_time
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_rights.last_right_name
     *
     * @return the value of view_rights.last_right_name
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public String getLastRightName() {
        return lastRightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_rights.last_right_name
     *
     * @param lastRightName the value for view_rights.last_right_name
     *
     * @mbg.generated Sat Jun 13 22:29:41 CST 2020
     */
    public void setLastRightName(String lastRightName) {
        this.lastRightName = lastRightName == null ? null : lastRightName.trim();
    }
}